name: AlwaysTime
version: 1.0
api-version: 1.15
author: OcelotcR
main: uk.ocelotcr.AlwaysTime

commands:
  alwaystime:
    description: Set to night or day to your current world.
    usage: /alwaystime [night/day]